### PR TITLE
auth_detail JSON logging

### PR DESCRIPTION
**Pull request by Loonride**
Fix `auth_detail` logging to be in JSON format

### CODE REVIEW

**Comment by yadudoc** [comment]
Looks like the tests are failing around the mocking code.

**Comment by yadudoc** [comment]
The PR looks pretty good though, we can merge once the tests are passing.

**Comment by Loonride** [comment]
@yadudoc I just added a try block to let tests pass since this isn't critical anyway, just logs

**Review by yadudoc — APPROVED** [review]
This should be fine.

**Pull request merged**
