### PR TITLE
Logging cleanup

### PR DESCRIPTION
**Pull request by yadudoc**
* Removes per-request logging wrappers that create excessive logging volume
* Cleaning up application logging to remove duplicate info
* Added json extra parsable info for improving debuggability

### CODE REVIEW

**Comment by yadudoc** [comment]
Related to [sc-12739]

**Comment by sirosen** [comment]
I agree with the decision to remove the before_request logging. However, I think it's useful to have a single message emitted after_request (during teardown). That message can be used to drive log metrics.

I'd eventually like to see something to the effect of
```python
@after_request
def post_request_logging(response):
    context = flask.g.logging_context
    write_log(
        {
            "event": "http_after_request",
            "context": context,
            "http": {
                "request_size": flask.request.content_length,  # or whatever fields
            }
        }
    )
    return response
```

and then we can build that `logging_context` object over the course of the request and do a single write at the end of it.

I don't expect us to get there in a single step. But, for the reason that I want to add this as a way of getting metric data, would it be okay to keep the `after_request` logging step, and just cut it all the way down to this?
```python
    @application.after_request
    def after_request(response):
        extra = {
            "path": request.path,
            "full_path": request.full_path,
            "method": request.method,
            "log_type": "after_request",
            "view_args": request.view_args,
        }
        logger.info("after_request", extra=extra)
        return response
```

**Comment by yadudoc** [comment]
@sirosen I agree that it would be good to have the after_request one. However, I think that should be done in a separate PR. I want to keep this one as minimal as possible, get it into dev, and have it tested there to confirm how far our logging volume drops.

**Review by sirosen — APPROVED** [review]
That's a reasonable stance. We'll add after_request logging back into the application after we have fixed some more of the issues with logging.

**Pull request merged**
